# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SixtCarSummoner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SixtCarSummoner
  pod 'Hero'
  pod 'SPAlert'

  target 'SixtCarSummonerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SixtCarSummonerUITests' do
    # Pods for testing
  end

end
